openapi: 3.0.3
info:
  title: Github Credential Service API
  description: Complete requests to Github API with confidential credentials
  license:
    name: Copyright (C) 2024 Trend Micro Inc. All rights reserved.
  version: 2.0.0
paths:
  /api/github/status:
    post:
      operationId: setCommitStatus
      summary: Set the status on a commit using the GitHub API
      description: Set the status on a commit using the GitHub API
      parameters:
        - $ref: '#/components/parameters/apiversion'
      requestBody:
        description: The request body to perform the GitHub API action
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - commit
                - status
              properties:
                commit:
                  type: object
                  required:
                    - org
                    - repo
                    - sha
                  description: Information about the commit
                  properties:
                    org:
                      type: string
                      description: The GitHub organization
                      enum:
                        - my-org-1
                        - my-org-2
                    repo:
                      type: string
                      description: The GitHub repository
                    sha:
                      type: string
                      description: The commit SHA
                status:
                  type: object
                  description: The specification of the status
                  properties:
                    state:
                      type: string
                      description: The state of the status
                      enum:
                        - failure
                        - pending
                        - success
                    target_url:
                      type: string
                      description: The URL to associate with this status
                    description:
                      type: string
                      description: A short description of the status
                    context:
                      type: string
                      description: A string label to differentiate this status from the status of other systems
      responses:
        '202':
          description: The API request has been accepted
          headers:
            Api-Version:
              $ref: '#/components/headers/Api-Version'
            Request-Id:
              $ref: '#/components/headers/Request-Id'
            Retry-After:
              $ref: '#/components/headers/Retry-After'
            Sunset:
              $ref: '#/components/headers/Sunset'
            Link:
              $ref: '#/components/headers/Link'
            Api-Notice:
              $ref: '#/components/headers/Api-Notice'
            Strict-Transport-Security:
              $ref: '#/components/headers/Strict-Transport-Security'
            Vary:
              $ref: '#/components/headers/Vary'
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: The response message
                    example: Accepted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '423':
          $ref: '#/components/responses/BodySizeToLarge'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GithubPostStatusFunction.Arn}/invocations
        credentials: 
          Fn::Sub: ${APIGatewayRole.Arn}
        httpMethod: POST
        type: aws_proxy
x-amazon-apigateway-gateway-responses: # Gateway response defined using CFN will not be properly linked to SAM; thus, defining API gateway response here will make sure SAM API correctly creates gateway response.
  DEFAULT_4XX:
    responseParameters:
      gatewayresponse.header.Strict-Transport-Security: "'max-age=63072000; includeSubDomains; preload'"
      gatewayresponse.header.Api-Version: "'v2'"
    responseTemplates:
      'application/json': '{"message": $context.error.messageString}'
  DEFAULT_5XX:
    responseParameters:
      gatewayresponse.header.Strict-Transport-Security: "'max-age=63072000; includeSubDomains; preload'"
      gatewayresponse.header.Api-Version: "'v2'"
    responseTemplates:
      'application/json': '{"message": $context.error.messageString}'

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message (optional)
          example: Error message
  parameters:
    apiversion:
      in: header
      name: Api-Version
      description: The API version used in this request.
      required: true
      schema:
        type: string
      example: v1
  headers:
    Api-Version:
      description: |-
        The API version used in this request.
      schema:
        type: string
        default: v1
      example: v1
    Api-Notice:
      description: |-
        If present, this header will include important API information.
        We will use this header as one way to notify you that a new API
        version is available or that the API you are using is going to
        be removed.
      schema:
        type: string
    Link:
      description: |-
        If this API endpoint has been deprecated, a `Link` header with the
        `sunset` relation type may be present with a link to human-readable
        article describing the API change.
      schema:
        type: string
    Request-Id:
      description: |-
        The request ID assigned to this request.
      schema:
        type: string
    Retry-After:
      description: |-
        The amount of time (in seconds) you should wait before trying this
        request again.
      schema:
        type: integer
    Sunset:
      description: |-
        If present, this API endpoint has been deprecated and may be
        removed at any point after the reported date. The timestamp is
        an HTTP date string in the format `Fri, 11 Nov 2018 11:11:11
        GMT`.
      schema:
        type: string
        format: datetime
    Strict-Transport-Security:
      description: |-
        Indicate that requests to this endpoint should be made over a secure
        transport mechanism.
      example: max-age=63072000; includeSubdomains; preload
      schema:
        type: string
    Vary:
      description: |-
        The service will respond with a `Vary` header indicating that responses
        vary depending on the `Origin` and `Authorization` request headers.
      example: 'Origin, Authorization'
      schema:
        type: string
  responses:
    BadRequest:
      description: Bad Request
      headers:
        Api-Version:
          $ref: '#/components/headers/Api-Version'
        Request-Id:
          $ref: '#/components/headers/Request-Id'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        Sunset:
          $ref: '#/components/headers/Sunset'
        Link:
          $ref: '#/components/headers/Link'
        Api-Notice:
          $ref: '#/components/headers/Api-Notice'
        Strict-Transport-Security:
          $ref: '#/components/headers/Strict-Transport-Security'
        Vary:
          $ref: '#/components/headers/Vary'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      headers:
        Api-Version:
          $ref: '#/components/headers/Api-Version'
        Request-Id:
          $ref: '#/components/headers/Request-Id'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        Sunset:
          $ref: '#/components/headers/Sunset'
        Link:
          $ref: '#/components/headers/Link'
        Api-Notice:
          $ref: '#/components/headers/Api-Notice'
        Strict-Transport-Security:
          $ref: '#/components/headers/Strict-Transport-Security'
        Vary:
          $ref: '#/components/headers/Vary'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      headers:
        Api-Version:
          $ref: '#/components/headers/Api-Version'
        Request-Id:
          $ref: '#/components/headers/Request-Id'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        Sunset:
          $ref: '#/components/headers/Sunset'
        Link:
          $ref: '#/components/headers/Link'
        Api-Notice:
          $ref: '#/components/headers/Api-Notice'
        Strict-Transport-Security:
          $ref: '#/components/headers/Strict-Transport-Security'
        Vary:
          $ref: '#/components/headers/Vary'
    Conflict:
      description: Conflict
      headers:
        Api-Version:
          $ref: '#/components/headers/Api-Version'
        Request-Id:
          $ref: '#/components/headers/Request-Id'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        Sunset:
          $ref: '#/components/headers/Sunset'
        Link:
          $ref: '#/components/headers/Link'
        Api-Notice:
          $ref: '#/components/headers/Api-Notice'
        Strict-Transport-Security:
          $ref: '#/components/headers/Strict-Transport-Security'
        Vary:
          $ref: '#/components/headers/Vary'
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: Error message (optional)
                example: Error message
    TooManyRequests:
      description: Too Many Requests
      headers:
        Api-Version:
          $ref: '#/components/headers/Api-Version'
        Request-Id:
          $ref: '#/components/headers/Request-Id'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        Sunset:
          $ref: '#/components/headers/Sunset'
        Link:
          $ref: '#/components/headers/Link'
        Api-Notice:
          $ref: '#/components/headers/Api-Notice'
        Strict-Transport-Security:
          $ref: '#/components/headers/Strict-Transport-Security'
        Vary:
          $ref: '#/components/headers/Vary'
    BodySizeToLarge:
      description: Body size too large
      headers:
        Api-Version:
          $ref: '#/components/headers/Api-Version'
        Request-Id:
          $ref: '#/components/headers/Request-Id'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        Sunset:
          $ref: '#/components/headers/Sunset'
        Link:
          $ref: '#/components/headers/Link'
        Api-Notice:
          $ref: '#/components/headers/Api-Notice'
        Strict-Transport-Security:
          $ref: '#/components/headers/Strict-Transport-Security'
        Vary:
          $ref: '#/components/headers/Vary'
    InternalServerError:
      description: Internal Server Error
      headers:
        Api-Version:
          $ref: '#/components/headers/Api-Version'
        Request-Id:
          $ref: '#/components/headers/Request-Id'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        Sunset:
          $ref: '#/components/headers/Sunset'
        Link:
          $ref: '#/components/headers/Link'
        Api-Notice:
          $ref: '#/components/headers/Api-Notice'
        Strict-Transport-Security:
          $ref: '#/components/headers/Strict-Transport-Security'
        Vary:
          $ref: '#/components/headers/Vary'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServiceUnavailable:
      description: Service Unavailable
      headers:
        Api-Version:
          $ref: '#/components/headers/Api-Version'
        Request-Id:
          $ref: '#/components/headers/Request-Id'
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        Sunset:
          $ref: '#/components/headers/Sunset'
        Link:
          $ref: '#/components/headers/Link'
        Api-Notice:
          $ref: '#/components/headers/Api-Notice'
        Strict-Transport-Security:
          $ref: '#/components/headers/Strict-Transport-Security'
        Vary:
          $ref: '#/components/headers/Vary'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'