Parameters:
  ResourceNamePrefix:
    Type: String
    Default: 'Git'
  ResourceBucket:
    Type: String
    Default: 'git-credential-service-artifacts'
  LogLevel:
    Type: String
    Default: ERROR

Resources:
  DataPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*GitStatusTokenSecret*'

  DataRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ResourceNamePrefix}-DataRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref 'DataPolicy'
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
              

  GitStatusTokenSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub ${ResourceNamePrefix}-GitStatusTokenSecret
      Description: API Token
      SecretString: 'PutYourSecretHere'

  GithubPostStatusFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ResourceNamePrefix}-GithubPostStatus'
      LoggingConfig:
        LogGroup: !Ref 'GithubPostStatusLog'
        ApplicationLogLevel: !Ref 'LogLevel'
        SystemLogLevel: WARN
        LogFormat: JSON
      Environment:
        Variables:
          GIT_STATUS_CREDENTIAL_NAME: !Ref 'GitStatusTokenSecret'
      Code:
        S3Bucket: !Sub '${ResourceBucket}'
        S3Key: 'lambdas/arm64/provided.al2/git-credential-service/latest/git-credential-service-lambda.zip'
      MemorySize: 256
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Role: !GetAtt 'DataRole.Arn'
      Timeout: 900
  GithubPostStatusLog:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupClass: STANDARD
      LogGroupName: !Sub '/aws/lambda/${ResourceNamePrefix}-GithubPostStatus'
      RetentionInDays: 14

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    DependsOn:
      - AccessLogGroup
      - APIGatewayRole
      - GithubPostStatusFunction
    Properties:
      Name: ${ResourceNamePrefix}-GithubCredentialAPI
      Body:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub 's3://${ResourceBucket}/api/openapi-githubcredential.yml'
      MinimumCompressionSize: 0
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayRestApi
    Properties:
      RestApiId: !Ref 'ApiGatewayRestApi'
      StageName: !Sub '${ResourceNamePrefix}-GithubCredentialAPIDeployment'
      StageDescription:
        AccessLogSetting:
          DestinationArn: !GetAtt AccessLogGroup.Arn
        MethodSettings:
          - ResourcePath: /~1api~1telemetry # must start with '/' and encode other '/' to '~1'
            HttpMethod: POST
            LoggingLevel: INFO
            MetricsEnabled: true
            ThrottlingRateLimit: 6000
            ThrottlingBurstLimit: 3000
        TracingEnabled: true
  APIGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: allow-api-gateway-to-invoke-Lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action: lambda:InvokeFunction
                Effect: Allow
                Resource: !GetAtt GithubPostStatusFunction.Arn
  AccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'GitHub-Credential-API-${ResourceNamePrefix}-AccessLogGroup'
      RetentionInDays: 14
